Repository AY2425S1-CS2113-W14-3/tp, pull requests merged in 2024-11, with the labels that each got.

#271 DG update
  docs/UML/editEntryCommandSequence.png
  docs/UML/editEntryCommandSequence.puml
Labels: prioirity.Low, type.Bug, status.done

#279 Update DateParser
  data/Budget.txt
  data/FinancialList.txt
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/duke/financial/Expense.java
  src/main/java/seedu/duke/financial/FinancialEntry.java
  src/main/java/seedu/duke/financial/Income.java
  src/main/java/seedu/duke/logic/Logic.java
  src/main/java/seedu/duke/parser/DateParser.java
  src/main/java/seedu/duke/storage/Storage.java
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
  src/test/java/seedu/duke/command/DateParserTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/EditEntryCommandTest.java
  src/test/java/seedu/duke/command/SeeAllEntriesCommandTest.java
  src/test/java/seedu/duke/command/SeeAllExpensesCommandTest.java
  src/test/java/seedu/duke/command/SeeAllIncomesCommandTest.java
  src/test/java/seedu/duke/logic/BudgetLogicTest.java
  src/test/java/seedu/duke/storage/StorageTest.java
  src/test/java/seedu/duke/ui/LogicTest.java
Labels: priority.High, type.Bug

#278 Edit UG
  docs/UserGuide.md
Labels: type.Bug
