Repository AY2425S1-CS2113-W14-3/tp, pull requests merged in 2024-10, with the labels that each got.

#50 Fix bug in FinancialEntry class constructor
  src/main/java/seedu/duke/financial/FinancialEntry.java
Labels: type.Bug

#64 Update AddExpenseCommandTest
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
Labels: type.Bug

#78 Littleme1032 Juven fix delete bug
  src/main/java/seedu/duke/command/DeleteCommand.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
Labels: type.Bug

#91 Edit AppUi
  src/main/java/seedu/duke/ui/AppUi.java
Labels: priority.High, type.Bug

#98 Update Junit to match date
  src/test/java/seedu/duke/command/AddExpenseCommandTest.java
  src/test/java/seedu/duke/command/AddIncomeCommandTest.java
  src/test/java/seedu/duke/command/DateParserTest.java
  src/test/java/seedu/duke/command/DeleteCommandTest.java
  src/test/java/seedu/duke/command/ExitCommandTest.java
  src/test/java/seedu/duke/command/HelpCommandTest.java
  src/test/java/seedu/duke/ui/AppUiTest.java
Labels: priority.Medium
